### ISSUE TITLE
Feature request: Support link reference definitions. 

### ISSUE THREAD

**Issue by NfNitLoop** [crosstype/node-html-markdown#15]
Instead of creating all links inline, it would help the readability of unrendered Markdown documents if there were an option to move all links to [link reference definitions] at the end of the document.

[link reference definitions]: https://spec.commonmark.org/0.30/#link-reference-definitions

Ex: 

```
Here is some text with a [link](https://0bin.net/paste/s735Z5wG#IFueVOPicYrnyDjhxp7NlMcFGG7N6WjYwyz9Lsgdubr) that can become distracting in the middle if plaintext. Especially if there are [multiple](https://www.google.com/) [links](https://www.wikipedia.org/) [close](https://www.github.com) to each other.
```

Would be much nicer to read as:

```
Here is some text with a [link] that can become distracting in the middle if plaintext. Especially if there are [multiple] [links] [close] to each other.

[link]: https://0bin.net/paste/s735Z5wG#IFueVOPicYrnyDjhxp7NlMcFGG7N6WjYwyz9Lsgdubr
[multiple]: https://www.google.com/
[links]: https://www.wikipedia.org/
[close]:  https://www.github.com
```

Or even with explicit link references like this, if that's easier to automate:

```
Here is some text with a [link][1] that can become distracting in the middle if plaintext. Especially if there are [multiple][2] [links][3] [close][4] to each other.

[1]: https://0bin.net/paste/s735Z5wG#IFueVOPicYrnyDjhxp7NlMcFGG7N6WjYwyz9Lsgdubr
[2]: https://www.google.com/
[3]: https://www.wikipedia.org/
[4]: https://www.github.com
```

This is a feature I really like in <https://pypi.org/project/html2text/>, and I see mentioned in <https://github.com/mixmark-io/turndown>

**Comment by nonara** [comment]
Great suggestion! Added to my queue.

**Comment by NfNitLoop** [comment]
Thanks! Looking forward to trying this out! 👍 (Though that’ll  probably be when the link space issue is fixed, since that’s a blocker for me.)

**Comment by nonara** [comment]
Added in [v1](https://github.com/crosstype/node-html-markdown/releases/tag/v1.0.0) via `useLinkReferenceDefinitions` option.

**Comment by nonara** [comment]
@NfNitLoop Sure thing. Working on that.

**Comment by NfNitLoop** [comment]
Finally got around to using this. Works great, thanks!
