### ISSUE TITLE
Bug: Whitespace not respected as single space between elements

### ISSUE THREAD

**Issue by NfNitLoop** [crosstype/node-html-markdown#16]
```typescript
import * as nhm from "https://cdn.skypack.dev/node-html-markdown@v0.1.7"

const service = new nhm.NodeHtmlMarkdown({})
function example(html: string) {
    console.log("input:")
    console.log(html)
    console.log("output:")
    console.log(service.translate(html))
}

// The space between these two links disappears:
example(`
    <a href="http://www.google.com">Link One</a> <a href="https://www.wikipedia.org/">Link Two</a>
`)
```

Output:

```
input:

    <a href="http://www.google.com">Link One</a> <a href="https://www.wikipedia.org/">Link Two</a>

output:
[Link One](http://www.google.com)[Link Two](https://www.wikipedia.org/)
```

## Maintainer's Note

This issue is due to the fact that trailing whitespace should be treated as a space between _any_ element. 

Therefore, this has a broader range of impact that `a` tags. Example: `<span>test</span> <span>test2</span>` improperly renders as `testtest2`

Our upstream parser does not add nodes or range information in order to get the whitespace. I am submitting a PR to fix this.

**Comment by nonara** [comment]
Thanks for the report! Looks like this is another upstream issue with the parser. I'm filing an issue, and I'll look into a PR
