### ISSUE TITLE
Blocking img elements?

### ISSUE THREAD

**Issue by Koyamie** [crosstype/node-html-markdown#27]
Hello, I was trying to block <img /> elements but it doesn't seem to be working.

Here is my nhm code:
```js
this.nhm = new NodeHtmlMarkdown({
  blockElements: ['IMG'],
  maxConsecutiveNewlines: 2,
});
```

**Comment by nonara** [comment]
Hi @Koyamie! 

`blockElements` refers to what are known in HTML spec as "Block Elements". You can read a bit about that here: https://www.w3schools.com/html/html_blocks.asp

I understand the confusion. It isn't actually referring to the ability to filter out elements, which I think is what you're referring to.

For that, try using `ignore` instead of `blockElements`.

Hope that helps!

**Comment by Koyamie** [comment]
> Hi @Koyamie!
> 
> `blockElements` refers to what are known in HTML spec as "Block Elements". You can read a bit about that here: https://www.w3schools.com/html/html_blocks.asp
> 
> I understand the confusion. It isn't actually referring to the ability to filter out elements, which I think is what you're referring to.
> 
> For that, try using `ignore` instead of `blockElements`.
> 
> Hope that helps!

Hello, sorry I should have tell that I have tried both `ignore` and `blockElements`.

Ignoring actually doesn't work with the img tag for me.

Appreciate the help.

**Comment by nonara** [comment]
Hmm. Seems to work here.

```ts
const { NodeHtmlMarkdown } = require('node-html-markdown')

const nhm = new NodeHtmlMarkdown(
  {
    ignore: [ 'img' ],
    maxConsecutiveNewlines: 2,
  }
);

console.log(nhm.translate('<body><img src="hello"></body>'))

// Result = ""
```

**Comment by Koyamie** [comment]
I don't understand what I have missed, after trying your version it works fine for me. I probably did something wrong when I was trying out myself.
Sorry for the mess and thanks for the help!

**Comment by nonara** [comment]
No problem! Happy you got it working. Take care!
