### ISSUE TITLE
[Feature] Support for tables

### ISSUE THREAD

**Issue by aliaksandr-savitski** [crosstype/node-html-markdown#30]
Hey! First of all thanks for the package! Works great!

I ran into a problem with transforming HTML tables into markdown tables. Seems like the package just omits table elements and pushes just text to the output. 

I use default options.

Any help with this one?

**Comment by nonara** [comment]
Thanks for the kind words! Glad to hear it's working for you.

At the moment, the library doesn't have translators for tables, though it wouldn't be too difficult to add. I'm pretty swamped, so I'm not sure how soon I'd be able to get to it, but I agree that it would be a valuable addition.

If you or anyone else is interested in contributing, I'd be glad to review and help get it merged.

**Comment by otolab** [comment]
I implemented it. Would you be willing to review it?
PR #32

**Comment by nonara** [comment]
Added in [v1.2.0](https://github.com/crosstype/node-html-markdown/releases/tag/v1.2.0)
