### ISSUE TITLE
Cannot skip custom tags

### ISSUE THREAD

**Issue by winlp4ever** [crosstype/node-html-markdown#31]
Hi, in my html I use some custom tags `inline-math` and `block-math` to encapsulate math formulas, for example
```html
<inline-math math='\alpha+\beta'></inline-math>
```
However, when using your library, I found that this tag is ignored with all contents inside it. Is there any option that allows the library to leave intact blocks of this kind.
Thanks a lot,

**Comment by nonara** [comment]
Thanks for the report! Sorry for the delay in getting back to you. I've been swamped lately.

I ran the following test:

```
    const html = `<inline-math math='\\alpha+\\beta'>1+2=4</inline-math>`
    const res = translate(html); // = '1+2=4'
```

This seems to be working for me. If you can provide me with an example that is not working, I'd be happy to take a look for you!

**Comment by NicolaiSchmid** [comment]
I think I have the same issue as @winlp4ever. While yes, the parser leaves the children of the custom tag intact, I want the parser to also return my tag, inline with the unrendered markdown. 
Input:
```
<h1>Heading</h1>
<inline-math math='\alpha+\beta'></inline-math>
```
Output:
```
# Heading
<inline-math math='\alpha+\beta'></inline-math>
```

The ignore-flag doesn't seem to be built for this purpose.

**Comment by nonara** [comment]
@NicolaiSchmid You could do that with a custom translator.

Something like this should work:

```
({ node }) =>
  ({
     recurse: false
     content: node.toString()
  })
```
