### ISSUE TITLE
perfStart and perfStop breaking code in the browser

### ISSUE THREAD

**Issue by taylorhadden** [crosstype/node-html-markdown#36]
The usage of `process.env.LOG_PERF` on lines 214 and 218 of utilities.ts is causing an exception when `translate()` is called within the browser.

I have had luck using the following patten to make code work across node and browser contexts:

```ts
if (typeof global === 'undefined') {
    // Browser code
}
else {
    // Node code
}
```

I can create a PR to add this. Is this desirable?

**Comment by Hrishikesh-K** [comment]
I'm having the same issue. At first I thought this is not compatible with browsers (because even the name sid `node`), but checked readme and it says it's supported in browsers.

**Comment by SettingDust** [comment]
Should removed by https://github.com/crosstype/node-html-markdown/blob/master/transformer.js. Maybe not working

**Comment by SettingDust** [comment]
For now can use `"node-html-markdown": "https://github.com/SettingDust/node-html-markdown"`

**Comment by nonara** [comment]
Very sorry for the delay on this! My backlog was overloaded and I didn't catch this. Thanks @SettingDust for the PR.

Merged

**Comment by thomasefbland** [comment]
This error is still in the code and still persists

**Comment by josiah-roberts** [comment]
+1, still broken.

**Comment by amin-pro** [comment]
Nov 2024 Still Broken

**Comment by delta6626** [comment]
Still broken
