### ISSUE TITLE
`can't access property "replace", res is undefined`

### ISSUE THREAD

**Issue by SettingDust** [crosstype/node-html-markdown#40]
`TextNode#text()` or `TextNode#trimmedText()` isn't usable with browser parser. It's should be [wholeText](https://developer.mozilla.org/zh-CN/docs/Web/API/Text/wholeText)

https://github.com/crosstype/node-html-markdown/blob/master/src/visitor.ts#L163=

**Comment by nonara** [comment]
Thank you for the report.

It looks like we'd need to implement [wholeText](https://developer.mozilla.org/en-US/docs/Web/API/Text/wholeText), as you mentioned.

I attempted to address this. If you get a chance, please let me know if the latest version covers this.
