### ISSUE TITLE
Hard Returns / <p> Tags

### ISSUE THREAD

**Issue by anthonygualandri** [crosstype/node-html-markdown#41]
Wanted to see if I can get some help understanding how I might set any applicable options to parse textual hard returns / <p> tags as putting a blank line break in the markdown so that there's paragraph space between things. Thanks!

**Comment by nonara** [comment]
Hi Anthony. Sorry for the late reply. I'm not sure I'm following. You should be able to accomplish what you're looking for tag-wise with custom translators, which I can help advise on.

Can you give me a more detailed example of what you want to do?
