### ISSUE TITLE
Incorrect italic parsing

### ISSUE THREAD

**Issue by emilmuller** [crosstype/node-html-markdown#44]
Hi

I found this:

`<p>H<em>ell</em>o, World!</p>`

Should not translate to `H_ell_o World!`, but rather `H*ell*o, World!`

Kind regards, Emil

**Comment by nonara** [comment]
Hi Emil. Thank you for the report.

It is set that way by design, but you can configure the delimiter by changing `emDelimiter` to `_`. See the [options](https://github.com/crosstype/node-html-markdown#options) section of the help.
