### ISSUE TITLE
inaccurate node engine

### ISSUE THREAD

**Issue by gusvargas** [crosstype/node-html-markdown#7]
https://github.com/crosstype/node-html-markdown/blob/4bf0b4d256152e81b4d7c3fcbe717b4b69eaf826/package.json#L47-L49

But the build is emitting code like:

```js
// dist/main.js
const ignoredElements = this.options.ignore?.concat(config_1.defaultIgnoreElements) ?? config_1.defaultIgnoreElements;
```

Which uses both optional chaining and nullish coalescing; features added in Node 14.

**Comment by nonara** [comment]
Should be sorted now, @gusvargas. Thanks again.
